# Generated by Django 6.1 on 2026-08-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='productspecification',
            name='stock_non_negative',
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='sku',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='productspecification',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='spec_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='skusequence',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='sku_sequence_singleton'),
        ),
    ]
