# Generated by Django 6.1 on 2026-09-01 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_base_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='products.product'),
        ),
    ]
