# Generated by Django 6.1 on 2026-09-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sold_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
