# Generated by Django 6.1 on 2026-08-31 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('PRODUCTION', 'Production'), ('ORDER', 'Order'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='e.g. Order # or Production #', max_length=100, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.productspecification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
